version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                # requirements.txtのパス（リポジトリのルートにある場合は"/"）
    schedule:
      interval: "daily"          # 更新頻度（例えば、"daily", "weekly", "monthly" から選択可能）
      time: "09:00"
      timezone: "Asia/Tokyo"
