name: 設計タスク
description: 設計タスク
title: "[:compass: 設計]: "
labels: ["設計"]
body:
  - type: markdown
    attributes:
      value: |
        設計対象について記述.
        `(Optional)`が付いている項目はオプション項目となります.

  - type: input
    id: target
    attributes:
      label: 設計対象種別(Optional)
      description: |
        設計対象を記述  
        > 例) データベース バックエンドサービス api ui 状態管理 システム構成 ミドルウェア構成 その他
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: 概要
    validations:
      required: true

  - type: textarea
    id: policy
    attributes:
      label: 設計方針(Optional)
      description: |
        設計を行う上での方針について記述する.
        ex) ユーザが継にどのような操作を行うか一目でわかるようなUIとする.
    validations:
      required: false

  - type: textarea
    id: constrains
    attributes:
      label: 設計上の制約条件(Optional)
      description: |
        設計を行う上でのする上での制約条件があれば記述する.
        ex) Material Designに添うようにコントラスト比を保ったカラーとする.
    validations:
      required: false

  - type: textarea
    id: task_list
    attributes:
      label: タスクリスト(Optional)
      description: |
        設計に必要となるサブタスクを記述ください.
        > サブタスクがIssue化されている場合は、`- [ ] #Issue番号`という形式で記述ください.
      placeholder: |
        サブタスクがIssue化されている場合は - [ ] #Issue番号 という形式で記述
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: check_item
    attributes:
      label: チェック項目(Optional)
      description: |
        設計作成後のチェック項目(あったら)を記述するのでもOK.
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: premise_task_list
    attributes:
      label: 前提Issue(Optional)
      description: |
        前提Issueを`- #Issue番号`というように記述ください.
        > Issue化されていない前提タスクについてはフリーテキストで記述.
      placeholder: |
        - #Issue番号 という形式で記述
    validations:
      required: false

  - type: textarea
    id: related_task_list
    attributes:
      label: 関連Issue(Optional)
      description: |
        関連Issueを`- #Issue番号`という形式で記述ください.
      placeholder: |
        - #Issue番号 という形式で記述
    validations:
      required: false
