name: テスト
description: テストタスク
title: "[:clipboard: テスト]: "
labels: ["テスト"]
body:
  - type: markdown
    attributes:
      value: |
        テスト内容について記述.
        `(Optional)`が付いている項目はオプション項目となります.

  - type: input
    id: target
    attributes:
      label: テスト対象種別(Optional)
      description: |
        テスト対象を記述  
        > 例) データベース バックエンドサービス api ui 状態管理 システム構成 ミドルウェア構成 その他
    validations:
     required: false

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: |
        テスト概要について記述します.
    validations:
      required: true

  - type: textarea
    id: task_list
    attributes:
      label: タスクリスト(Optional)
      description: |
        設計に必要となるサブタスクを記述ください.
        > サブタスクがIssue化されている場合は、`- [ ] #Issue番号`という形式で記述ください.
      placeholder: |
        サブタスクがIssue化されている場合は - [ ] #Issue番号 という形式で記述
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: premise_task_list
    attributes:
      label: 前提Issue(Optional)
      description: |
        前提Issueを`- #Issue番号`というように記述ください.
        > Issue化されていない前提タスクについてはフリーテキストで記述.
      placeholder: |
        - #Issue番号 という形式で記述
    validations:
      required: false

  - type: textarea
    id: related_task_list
    attributes:
      label: 関連Issue(Optional)
      description: |
        関連Issueを`- #Issue番号`という形式で記述ください.
      placeholder: |
        - #Issue番号 という形式で記述
    validations:
      required: false
