name: OWASP Zap Scan
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"

      - name: Start the Flask application
        run: |
          nohup python ./vulnerability_codes/src/app.py &
          echo $! > flask_pid.txt
          sleep 10

      # Loginを行う場合
      # - name: Login to Flask application
      #   run: |
      #     curl -X POST http://127.0.0.1:5000/login \
      #     -H "Content-Type: application/x-www-form-urlencoded" \
      #     -d "user_id=sato2&password=st_pass"

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        timeout-minutes: 40
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://127.0.0.1:5000'
          # rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d'
          issue_title: 'ZAP Scan Report'
          artifact_name: 'zap_report'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_report

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: ZAP Scan Report
          content-filepath: zap_report/report.html
          labels: zap-scan

      - name: Stop the Flask application
        run: |
          kill $(cat flask_pid.txt)
