name: OWASP Zap Scan

on: [push]

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"

      - name: Start the application
        run: |
          python .\vulnerability_codes\src\app.py

    
      # - name: ZAP Scan
      #   uses: zaproxy/action-full-scan@v0.11.0
      #   timeout-minutes: 40
      #   with:
      #     token: ${{ secrets.MY_PATH }}
      #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
      #     target: 'http://localhost:8080'
      #     rules_file_name: '.zap/rules.tsv'
      #     cmd_options: '-a'