name: zap_scan
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: test run
        run: ls -la
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        timeout-minutes: 40
        with:
          token: ${{ secrets.MY_PATH }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'